_wandb:
    value:
        cli_version: 0.18.0
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 1
                - 9
                - 11
                - 41
                - 49
                - 51
                - 55
                - 63
                - 71
                - 103
                - 105
            "2":
                - 1
                - 9
                - 11
                - 41
                - 49
                - 51
                - 55
                - 63
                - 71
                - 103
                - 105
            "3":
                - 23
                - 55
            "4": 3.12.4
            "5": 0.18.0
            "6": 4.45.2
            "8":
                - 5
            "12": 0.18.0
            "13": linux-x86_64
